package zad1.src.commandsAndInstructions;

public enum Commands {
    NR_ROUNDS,
    BOARD_SIZE_X,
    BOARD_SIZE_Y,
    BEGIN_NR_ROBS,
    BEGIN_PROGR,
    BEGIN_ENERGY,
    FOOD_QUALITY,
    FOOD_GROWTH,
    ROUND_COST,
    PROB_MULTIPLY,
    PART_OF_PARENT_ENERGY,
    MULTIPLY_LIMIT,
    PROB_REM_COMMAND,
    PROB_ADD_COMMAND,
    INSTRUCTIONS,
    PROB_CHANGE_COMMAND,
    OUTPUT_FREQ
}
